name: flutter_tv
description: Flutter TV App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  #ThirdParty
  video_player: ^2.1.1
  http: ^0.13.3
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  platform_svg: ^0.0.2
  #bloc
  flutter_bloc: ^6.0.5
  equatable: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/bloques/

  fonts:
    - family: Helvetica Neu
      fonts:
        - asset: fonts/HelveticaNeue-Light.ttf
          weight: 100
        - asset: fonts/Helvetica-Neu-Bold.ttf
          weight: 300
        - asset: fonts/HelveticaNeue-Medium.ttf
          weight: 200
    - family: Cocogoose
      fonts:
        - asset: fonts/cocogoose/Cocogoose-Pro-trial.ttf
          weight: 800
        - asset: fonts/cocogoose/Cocogoose-Pro-Ultralight-trial.ttf
          weight: 300
        - asset: fonts/cocogoose/Cocogoose-Pro-Semilight-trial.ttf
          weight: 400
        - asset: fonts/cocogoose/Cocogoose-Pro-Light-Italic-trial.ttf
          weight: 200
        - asset: fonts/cocogoose/Cocogoose-Pro-Light-trial.ttf
          weight: 100
    - family: Alongsanss
      fonts:
        - asset: fonts/alongsanss/AlongSanss2-Light.otf
          weight: 100
        - asset: fonts/alongsanss/AlongSanss2-Medium.otf
          weight: 200
        - asset: fonts/alongsanss/AlongSanss2-Regular.otf
          weight: 300
        - asset: fonts/alongsanss/AlongSanss2-Bold.otf
          weight: 900